# Generated by Django 3.1.7 on 2021-04-01 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210401_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id', 'created_at', 'updated_at', 'user', 'title', 'body', 'slug']},
        ),
    ]
